apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: codeurjc/webgatos2-scalable:0.0.1
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        - name: DATABASE_SCHEMA
          value: webapp_db
        - name: DATABASE_PASS
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 8080
      name: webapp
